package com.demarco.flatpak;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import org.gradle.api.DefaultTask;
import org.gradle.api.provider.Property;
import org.gradle.api.tasks.Input;
import org.gradle.api.tasks.TaskAction;

public abstract class GenerateFlatpakManifestTask extends DefaultTask 
{
	@Input
	public abstract Property<String> getAppId();

	@Input
	public abstract Property<String> getCommand();

	@TaskAction
	public void generate() 
	{
		String appId = getAppId().isPresent() ? getAppId().get() : "org.example." + getProject().getName();
		String command = getCommand().isPresent() ? getCommand().get() : "launch.sh";
        
		String jarName = getProject().getTasks().findByName("bootJar") != null 
            		? "blueberry-irrigation.jar" 
            		: getProject().getName() + "-" + getProject().getVersion() + ".jar";

		File outputDir = new File(getProject().getBuildDir(), "flatpak");
		if (!outputDir.exists()) 
		{
			outputDir.mkdirs();
		}

        // ---- 1. Generate Manifest JSON (With Local Sources Block) ----
        File jsonFile = new File(outputDir, appId + ".json");
     // Inside GenerateFlatpakManifestTask.java, find your JSON block and update it to look like this:
     // Inside GenerateFlatpakManifestTask.java, update your JSON string builder block exactly like this:
     // Inside GenerateFlatpakManifestTask.java, replace your JSON block with this production version:
        String jsonManifest = "{\n" +
                "  \"id\": \"" + appId + "\",\n" +
                "  \"runtime\": \"org.freedesktop.Platform\",\n" +
                "  \"runtime-version\": \"25.08\",\n" +
                "  \"sdk\": \"org.freedesktop.Sdk\",\n" +
                "  \"sdk-extensions\": [\"org.freedesktop.Sdk.Extension.openjdk21\"],\n" +
                "  \"command\": \"" + command + "\",\n" +
                "  \"finish-args\": [\n" +
                "    \"--share=network\",\n" +
                "    \"--device=all\",\n" +
                "    \"--filesystem=/sys\",\n" +
                "    \"--filesystem=host-etc:ro\",\n" +
                "    \"--env=PATH=/usr/bin:/bin:/app/bin:/app/jre/bin\"\n" + // <--- Maps the production path to your bundled JRE
                "  ],\n" +
                "  \"modules\": [\n" +
                "    {\n" +
                "      \"name\": \"openjdk\",\n" + // <--- ADD THIS MODULE STEP: Extracts and cooks JRE into the application payload permanently
                "      \"buildsystem\": \"simple\",\n" +
                "      \"build-commands\": [\n" +
                "        \"/usr/lib/sdk/openjdk21/install.sh\"\n" +
                "      ]\n" +
                "    },\n" +
                "    {\n" +
                "      \"name\": \"" + getProject().getName() + "\",\n" +
                "      \"buildsystem\": \"simple\",\n" +
                "      \"build-commands\": [\n" +
                "        \"install -D " + jarName + " /app/share/java/" + jarName + "\",\n" +
                "        \"install -D " + command + " /app/bin/" + command + "\"\n" +
                "      ],\n" +
                "      \"sources\": [\n" +
                "        {\n" +
                "          \"type\": \"file\",\n" +
                "          \"path\": \"" + jarName + "\"\n" +
                "        },\n" +
                "        {\n" +
                "          \"type\": \"file\",\n" +
                "          \"path\": \"" + command + "\"\n" +
                "        }\n" +
                "      ]\n" +
                "    }\n" +
                "  ]\n" +
                "}";

        try (FileWriter writer = new FileWriter(jsonFile)) 
	{
            writer.write(jsonManifest);
            getLogger().lifecycle("Generated Flathub manifest: " + jsonFile.getAbsolutePath());
        } 
	catch (IOException e) 
	{
            getLogger().error("Failed to write JSON manifest", e);
        }

        // ---- 2. Generate Launch Script (launch.sh) ----
        File scriptFile = new File(outputDir, command);
        String shellScript = "#!/bin/sh\n" +
                "# Automatically generated by flatpak-generator-plugin\n" +
                "# Paul DeMarco pjdemarco@gmail.com 2026\n" +
                "exec java -jar /app/share/java/" + jarName + " \"$@\"\n";

        try (FileWriter writer = new FileWriter(scriptFile)) 
	{
            writer.write(shellScript);
            scriptFile.setExecutable(true, false);
            getLogger().lifecycle("Generated executable wrapper: " + scriptFile.getAbsolutePath());
        } 
	catch (IOException e) 
	{
            getLogger().error("Failed to write launch script file", e);
        }
    }
}
